package org.firstinspires.ftc.teamcode.Tests;

import com.qualcomm.robotcore.eventloop.opmode.LinearOpMode;
import com.qualcomm.robotcore.eventloop.opmode.TeleOp;
import org.firstinspires.ftc.robotcore.external.hardware.camera.WebcamName;
import org.firstinspires.ftc.vision.VisionPortal;
import org.firstinspires.ftc.vision.apriltag.AprilTagDetection;
import org.firstinspires.ftc.vision.apriltag.AprilTagProcessor;
// The AprilTagGameDatabase import is fine, but not strictly required for this specific Opmode's logic
// as the metadata is accessed directly from the detection object.
// Uhh, Randy is not sure this code will exactly work for this season, as Google AI didn't know what
// the april tag IDs are. Gavin suggested that it might be "20" but Randy doesn't understand the concept
// quite yet of Pipelines. So this code should be double checked, maybe if Gavin has the time after
// this next tournament (Nov 15)
// Code generated by Gemini.

import java.util.List;
import java.lang.Math;

@TeleOp(name = "FieldPositionCalculator", group = "Linear OpMode")
public class RandyLimeLightFieldPositionSystem extends LinearOpMode {

    private VisionPortal visionPortal;
    private AprilTagProcessor aprilTag;

    // We use a placeholder for a specific tag ID you might want to target (e.g., Tag 5 for DECODE goal)
    private static final int TARGET_TAG_ID = 5;

    @Override
    public void runOpMode() {
        // Initialize the AprilTag processor
        aprilTag = AprilTagProcessor.easyCreateWithDefaults();

        // Initialize the Vision Portal (assuming a webcam named "Webcam 1")
        visionPortal = VisionPortal.easyCreateWithDefaults(
                hardwareMap.get(WebcamName.class, "Webcam 1"), aprilTag);

        telemetry.addData("Status", "Initialized. Waiting for detections...");
        telemetry.update();

        waitForStart();

        while (opModeIsActive()) {
            // Get a list of all detected tags in the current frame
            List<AprilTagDetection> currentDetections = aprilTag.getDetections();

            for (AprilTagDetection detection : currentDetections) {
                // Check if we found the target tag AND it has metadata (field position info)
                if (detection.id == TARGET_TAG_ID && detection.metadata != null) {

                    // We found our target tag.
                    // The SDK populates 'metadata' with the tag's known field position/orientation.

                    double tagX = detection.metadata.fieldPosition.get(0);
                    double tagY = detection.metadata.fieldPosition.get(1);

                    // NOTE: The FTC SDK does not explicitly store the tag's Yaw in metadata as a single field.
                    // You typically derive or hardcode this from the known field layout.
                    // We will keep your hardcoded 45 degrees assumption for now, but be aware this may need adjustment for
                    // your specific game's field layout and tag ID.
                    double tagYaw = 45.0;

                    // Get the measured values from the detection object
                    double distance = detection.ftcPose.range; // Range in inches
                    double angleOffset = detection.ftcPose.bearing; // Bearing (tx) in degrees
                    // Make sure to define the april tags x and y field coordinates in the above line
                    // This code generated by AI, make sure to double check that it's correct.

                    // Calculate the robot's field position using the function below
                    double[] robotPosition = calculateRobotPosition(tagX, tagY, tagYaw, distance, angleOffset);
                    double robotX = robotPosition[0];
                    double robotY = robotPosition[1];

                    // Report findings
                    telemetry.addData("Target Tag", "ID %d found", detection.id);
                    telemetry.addData("Robot Pos X", "%.2f inches", robotX);
                    telemetry.addData("Robot Pos Y", "%.2f inches", robotY);
                    telemetry.addData("Distance", "%.2f inches", distance);
                    telemetry.addData("Angle Offset (Bearing)", "%.2f deg", angleOffset);
                    // Stop iterating if we found the one tag we care about this frame (optional)
                    break;
                }
            }
            telemetry.update();
        }
    }

    /**
     * Calculates the robot's estimated field position based on a single AprilTag detection,
     * without needing the robot's IMU heading.
     *
     * @param tagX The known X coordinate of the AprilTag on the field (inches).
     * @param tagY The known Y coordinate of the AprilTag on the field (inches).
     * @param tagYaw The known yaw orientation of the AprilTag on the field (degrees).
     * @param distance The measured distance to the AprilTag (inches).
     * @param angleOffset The measured horizontal angle offset/bearing to the AprilTag (degrees).
     * @return A double array containing the estimated [robotX, robotY] coordinates in inches.
     */
    public double[] calculateRobotPosition(double tagX, double tagY, double tagYaw, double distance, double angleOffset) {
        // Convert all angles to radians for Java Math functions
        double tagYawRad = Math.toRadians(tagYaw);
        double angleOffsetRad = Math.toRadians(angleOffset);

        // The key insight: The angle from the TAG to the ROBOT is the tag's field orientation
        // plus the measured bearing. The 90-degree offset accounts for the fact that
        // the tag's yaw is often defined along its normal vector (pointing outwards).

        // This calculates the absolute field angle from the positive X axis pointing to the robot.
        double angleTagToRobot = tagYawRad + Math.toRadians(90) + angleOffsetRad;

        // Calculate the robot's position relative to the tag's position
        // We use subtraction here because we are calculating where the robot is located relative *to* the tag's location.
        double robotX = tagX - (distance * Math.cos(angleTagToRobot));
        double robotY = tagY - (distance * Math.sin(angleTagToRobot));

        return new double[]{robotX, robotY};
    }
}
